name: perf_benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '0 */8 * * *' # Run workflow threee times a day

jobs:
  benchmark_fasttrack_ml:
    name: FastTrackML Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Grant write permission
        run: chmod 777 ./

      - name: Run Performance tests using docker compose
        run: docker-compose up performance-tests
        env:
          DOCKER_BUILDKIT: 1

      - name: Upload raw benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: performance_data.csv
          path: performance_data.csv


        